= SMB Connector
:toc:
toc::[]


[[overview]]
== Overview


Anypoint Connector for SMB provides the capability to perform operations (such as create directory, list directory contents, delete a directory, read a file, write a file, delete a file) against a Windows SMB share.

For details on this release see:

* link:/doc/release-notes.adoc[Connector Release Notes]

This document assumes that you are familiar with Mule, Anypoint Connectors, Anypoint Studio, Mule Concepts, and Global Elements.

[[install]]
== How to Install

You can install the connector in Anypoint Studio using the instructions in
link:https://docs.mulesoft.com/mule-runtime/3.9/installing-connectors[Installing Connectors].

If you are upgrading from a previous version of the connector, a small popup appears in the bottom right corner of Anypoint Studio with the "Updates Available" message. Click the popup and follow the prompts to install the latest version.

[[ns-schema]]
== Connector Namespace and Schema

When designing your application in Anypoint Studio, when you drag the connector from the palette onto the Anypoint Studio canvas, Studio automatically populates the XML code with the connector *namespace* and *schema location*.

* *Namespace*: `+http://www.mulesoft.org/schema/mule/smb+` +
* *Schema Location*: `+http://www.mulesoft.org/schema/mule/smb/current/mule-smb.xsd+`

[TIP]
If you are manually coding the Mule application in Studio's XML editor or another text editor, define the namespace and schema location in the header of your *Configuration XML*, inside the `<mule>` tag.

[source, xml, linenums]
----
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:connector="http://www.mulesoft.org/schema/mule/smb"
      xsi:schemaLocation="
               http://www.mulesoft.org/schema/mule/core
               http://www.mulesoft.org/schema/mule/core/current/mule.xsd
               http://www.mulesoft.org/schema/mule/smb
               http://www.mulesoft.org/schema/mule/smb/current/mule-smb.xsd">

      <!-- put your global configuration elements and flows here -->

</mule>
----

NOTE: Use `current` in the schema path. Studio interprets this to the current Mule version.

[[maven]]
== Maven Dependency Information

For Maven dependency management, include this XML snippet in your `pom.xml` file.

[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.modules</groupId>
    <artifactId>mule-module-smb</artifactId>
    <version>1.2.0</version>
</dependency>
----

Inside the `<version>` tags, put the desired version number, the word `RELEASE` for the latest release, or `SNAPSHOT` for the latest available version.

[[configure]]
== How to Configure

Place the connector in your flow as applicable for your use case.

To use the SMB connector in your Mule application, you must configure a global SMB element that can be used by the SMB connector, smb:config.

*smb-config*

[%header%autowidth.spread]
|===
|Field |Description
|Domain |Enter a Windows domain for the user to log in with.
|Host |Hostname of server hosting SMB share.
|Share |Named path of the SMB share.
|Username |Enter the username to log in with. Setting the value to "guest" indicates that guest connectivity should be used and no password is required. Setting the value to "anonymous" indicates that anonymous connectivity should be used and no password is required. These values are reserved to indicate these access types.
|Password |Enter the corresponding password.
|Connection timeout |Timeout for connection, in milliseconds.
|File age |Age of file required to perform operations on it, in milliseconds.
|===


[[operations]]
== Operations

[%header,cols="20%,80%"]
|===
|Name |Description
|File read |Reads the contents of a file from the SMB share
|File write |Writes data out to a file, optional property to append data to an existing file
|File delete |Delete a file from the SMB share
|Directory create |Create a new directory on the SMB share
|Directory list |List the contents of a directory on the SMB share
|Directory delete |Delete a directory from the SMB share
|===

=== File read

Reads the contents of a file from the SMB share, this can be wrapped in a poll scope at the start of a flow or used mid-flow to retrieve some data. Obeys minimum file age requirements.

*Parameters*

[%header,cols="20%,20%,20%,20%,20%"]
|===
|Name |Type |Description |Default Value |Required
|Directory Name |String |Directory where file is located | |X
|File Name |String |Name of file to read in | |X
|Delete after reading |Boolean |Should the file be deleted after reading |No |
|===

*Output*

byte[]

*For Configurations*

smb-config

=== File write

Writes the specified file content to a file on an SMB share, this can be wrapped in a poll scope at the start of a flow or used mid-flow.

*Parameters*

[%header,cols="20%,20%,20%,20%,20%"]
|===
|Name |Type |Description |Default Value |Required
|Directory Name |String |Directory where file is located | |X
|File Name |String |Name of file to write to | |X
|File content reference |String or InputStream or byte[] |Content to write to file |#[payload] |X
|Encoding | |character encoding of contents to write |UTF-8 |X for String content
|Append to file |Boolean |Should the content be appended to the file otherwise overwrite content |No |
|===

*Output*

void

*For Configurations*

smb-config

=== File delete

Delete the specified file from the SMB share, this can be wrapped in a poll scope at the start of a flow or used mid-flow. Returns true if successful.  Obeys minimum file age requirements.

*Parameters*

[%header,cols="20%,20%,20%,20%,20%"]
|===
|Name |Type |Description |Default Value |Required
|Directory Name |String |Directory where file is located | |X
|File Name |String |Name of file to delete | |X
|===

*Output*

boolean

*For Configurations*

smb-config

=== Directory create

Create the specified directory on the SMB share, this can be wrapped in a poll scope at the start of a flow or used mid-flow. Returns true if successful.

*Parameters*

[%header,cols="20%,20%,20%,20%,20%"]
|===
|Name |Type |Description |Default Value |Required
|Directory Name |String |Name of directory to create | |X
|===

*Output*

boolean

*For Configurations*

smb-config

=== Directory list

List the contents of specified directory from the SMB share, this can be wrapped in a poll scope at the start of a flow or used mid-flow. Results include only items that are older than the minimum file age.

*Parameters*

[%header,cols="20%,20%,20%,20%,20%"]
|===
|Name |Type |Description |Default Value |Required
|Directory Name |String |Name of directory to search in | |X
|Wildcard |String |DOS style wildcard filter |*.* |
|===

*Output*

List<String>

*For Configurations*

smb-config

=== Directory delete

Delete the specified directory from the SMB share, this can be wrapped in a poll scope at the start of a flow or used mid-flow. Returns true if successful.

*Parameters*

[%header,cols="20%,20%,20%,20%,20%"]
|===
|Name |Type |Description |Default Value |Required
|Directory Name |String |Name of directory to delete | |X
|Recursive delete |Boolean |Should the delete be executed recursively |No |
|===

*Output*

boolean

*For Configurations*

smb-config

